
#BUILD_DIRS = 0Subho_Resume TeachingStatement ResearchStatement ListOfPublications

all:
    number=1 ; while [[ $$number -le 10 ]] ; do \
        echo $$number ; \
        ((number = number + 1)) ; \
    done

#all:
#    for tar_dir in $(BUILD_DIRS); do \
#        echo "Building: "$$tar_dir ; \
#        $(MAKE) -C $$tar_dir; \
#    done
#clean:
#    for tar_ in $(BUILD_DIRS); do \
#        $(MAKE) -C $$tar_dir clean; \
#    done